{
  config,
  lib,
  pkgs,
  username,
  ...
}:

{
  home.packages = with pkgs; [ czkawka ];

  xdg.configFile."czkawka/czkawka_gui_config_4.txt".text = ''
    --confirm_deletion_all_files_in_group
    true
    --broken_files_audio
    true
    --similar_images_similarity
    0
    --broken_files_pdf
    true
    --delete_to_trash
    false
    --hide_hard_links
    true
    --thread_number
    0
    --number_of_biggest_files
    50
    --excluded_directories
    /proc
    /dev
    /sys
    /run
    /snap
    /home/${username}/Games
    /home/${username}/.local/share/Steam
    --video_delete_outdated_cache_entries
    true
    --broken_files_archive
    true
    --combo_box_image_resize_algorithm
    0
    --combo_box_image_hash_size
    1
    --similar_images_ignore_same_size
    false
    --music_compare_by_title
    false
    --combo_box_duplicate_check_method
    0
    --duplicate_preview_image
    true
    --use_prehash_cache
    true
    --broken_files_image
    true
    --use_json_cache_file
    false
    --music_approximate_comparison
    false
    --image_preview_image
    true
    --maximal_file_size
    999999999999
    --minimal_prehash_cache_size
    0
    --minimal_cache_size
    257144
    --combo_box_big_files_mode
    0
    --duplicate_name_case_sensitive
    false
    --allowed_extensions

    --ignore_other_filesystems
    false
    --use_cache
    true
    --similar_videos_ignore_same_size
    false
    --use_rust_libraries_to_preview
    true
    --duplicate_delete_outdated_cache_entries
    true
    --show_bottom_text_panel
    true
    --save_at_exit
    true
    --excluded_items
    */.git/*,*/node_modules/*,*/lost+found/*,*/Trash/*,*/.Trash-*/*,*/snap/*,/home/*/.cache/*
    --confirm_deletion_files
    true
    --minimal_file_size
    16384
    --language
    en
    --combo_box_duplicate_hash_type
    0
    --combo_box_image_hash_type
    0
    --included_directories
    /home/${username}
    --load_at_start
    true
    --similar_videos_similarity
    15
    --image_delete_outdated_cache_entries
    true
  '';
}
