keys:
  - &users:
    - &adam0 3666B440B0E872931B8E78596CFFE3FBA5DD84B9
  - &hosts:
    - &desktop
    - &laptop
    - &vm
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          - *adam0
      - age:
          - *desktop
          - *laptop
          - *vm
